# Generated by Django 2.0.6 on 2018-06-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('contents', models.CharField(max_length=500)),
                ('count', models.IntegerField(max_length=10)),
                ('regdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
