# Generated by Django 2.0.6 on 2018-06-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='no',
            field=models.IntegerField(),
        ),
    ]
