# Generated by Django 2.0.6 on 2018-06-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180628_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='no',
        ),
    ]
