# Generated by Django 2.0.6 on 2018-06-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_board_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
